name: 'Udacity Frontend Integration Workflow'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: 'Code linting'
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Setup dependencies 
        uses: actions/setup-node@v3
        with:
          node-version: latest 
      - name: Install dependencies
        run: npm install
      
      - name: Fix eslint issues

      - name: Run linting
        run: npm run lint
        env:
          FAIL_LINT: true
  test:
    name: 'Code testing'
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Setup dependencies 
        uses: actions/setup-node@v3
        with:
          node-version: latest 
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
  build:
    name: 'Code building'
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build docker image without pushing it 
        run: docker buildx build --load -t frontend:latest .
      